### ISSUE TITLE
Error when loading a model when optimize is true

### ISSUE THREAD

**Issue by Lev-Stambler** [arition/torch-js#15]
When loading a fine tuned DistilBERT model, I get the following error 

```
Error {
    context: "Translating node #32 \"NonZero_16\" NonZero ToTypedTranslator",
    source: "Node #32 \"NonZero_16\" NonZero can not be typed",
}
```

I was wondering if there is any known reason for this?

My code:
```
const model = await tractjs.load("qa_model.onnx", {
    // inputFacts: {
    //   0: ["int32", [1, 512]],
    // },
    // optimize: false,
  });
  
```

**Comment by arition** [comment]
I think you posted this issue in a wrong repo. This repo is for torch-js, and it only accepts torchscript models, not ONNX. 
You should post this issue to https://github.com/bminixhofer/tractjs.
