### ISSUE TITLE
Add "image to tensor" load support.

### ISSUE THREAD

**Issue by RandGor** [arition/torch-js#20]
Hello! I am trying to run my model with input of image (1x3x256x256 tensors). I already generated random tensor with this shape - everything works well.
But I have a question: how can I load image as tensor? For example, I have image and loading it this way, but it now works.

fs.readFile('im.jpg', (err, data) => {
    console.log(torch.tensor(data))
})

**Comment by arition** [comment]
You need to use an image processing library to read the image and get the raw buffer. For example, check [sharp](https://sharp.pixelplumbing.com/api-output#tobuffer). After you get the buffer, you can use `torch.tensor` to convert buffer to tensor.
