### ISSUE TITLE
Does not work under MacOS

### ISSUE THREAD

**Issue by arition** [arition/torch-js#7]
@raghavmecheri #6 

```
dlopen(/Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node, 1): Library not loaded: @rpath/libc10.dylib
      Referenced from: /Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node
      Reason: image not found
```

**Comment by raghavmecheri** [comment]
> @raghavmecheri #6
> 
> ```
> dlopen(/Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node, 1): Library not loaded: @rpath/libc10.dylib
>       Referenced from: /Users/raghav/Projects/[PROJECTNAME]/node_modules/@arition/torch-js/build/Release/torch-js.node
>       Reason: image not found
> ```
I think the below discussion post is a good starting point -- @arition any ideas?
https://discuss.pytorch.org/t/how-to-make-c-programs-portable/68401

**Comment by arition** [comment]
I think the issue is caused by the cmake library import mechanisms under MacOS. The cmake always link the library using absolute path on building. Since I introduced the `prebuild` tool recently, the library path on github action's machine are different from the path on your machine. 

Related cmake docs and discussion:

https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

 https://github.com/conan-io/conan/issues/3996

From the docs I think add the following code to cmakelists can solve the problem.

```
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(MACOS TRUE)
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
endif()
```

However, I do not have a MacOS machine, so I cannot test if it works. If you want to give it a try, you can make a pull request and download the pull request build artifact for MacOS. Then, replace the `torch-js` binary in your `node_modules` to the downloaded one and test if it works.

Another way to check if it works is to check the `@rpath` of the built `torch-js.node` using `otool -l`.

**Comment by raghavmecheri** [comment]
@arition Unfortunately, none of the situations I found online to make this work are working out. I tried a large number, right from using the `@executable_path`, to using what you've listed above.

Do you think it makes sense to prebuild for Linux and Windows, and just build on install for MacOS?

EDIT: Can confirm that this is an issue on Linux as well, not sure if the prebuild works only on Windows?

**Comment by arition** [comment]
I think setting the ```DYLD_LIBRARY_PATH``` may fix the issue, can you try pr #9?

**Comment by raghavmecheri** [comment]
Just going full circle here and confirming that #9 isn't the way to go. @arition Lemme know if you want me to remove the prebuild stuff on MacOS/Linux if you're busy today, may have some time over the second half of the day :)

**Comment by arition** [comment]
I have already delete the prebuild from github release. The prebuild script should no longer be able to download prebuilds on MacOS and Linux.

**Comment by raghavmecheri** [comment]
> I have already delete the prebuild from github release. The prebuild script should no longer be able to download prebuilds on MacOS and Linux.

Do we need to bump the version on npm or something? `yarn add torch-js@npm:@arition/torch-js` still installs the prebuilt version for me

**Comment by arition** [comment]
> > I have already delete the prebuild from github release. The prebuild script should no longer be able to download prebuilds on MacOS and Linux.
> 
> Do we need to bump the version on npm or something? `yarn add torch-js@npm:@arition/torch-js` still installs the prebuilt version for me

I tried on my linux machine and it do a build install. Maybe cache on your machine?

**Comment by raghavmecheri** [comment]
> > > I have already delete the prebuild from github release. The prebuild script should no longer be able to download prebuilds on MacOS and Linux.
> > 
> > 
> > Do we need to bump the version on npm or something? `yarn add torch-js@npm:@arition/torch-js` still installs the prebuilt version for me
> 
> I tried on my linux machine and it do a build install. Maybe cache on your machine?

Yep -- prebuild has its own cache folder that I wasn't aware of -- fixed it :)
